development:
  adapter: postgresql
  database: simple-android-service_dev
  username: postgres
  password: 123456
  pool: 5
  host: localhost
  timeout: 5000
test:
  adapter: postgresql
  database: simple-android-service_test
  username: postgres
  password: 123456
  pool: 5
  host: localhost
  timeout: 5000